database: weRelate
user: jeremy
startDate: 2000-01-01 # Date of first edit
endDate: 2015-12-31 # Date of most recent edit
timeDelta: 30 # Days between periods of interest (for creating networks or behavior summaries
nodeList: ~/Programming/WeRelate/DataFiles/overFiveEditsStartBefore20120603.csv
saveLocation: ~/Programming/WeRelate/DataFiles/ThesisNetworks/
commDelta: 7 # Max time between communication edits. 
collabDelta: 30 # Max time between collaboration edits
cutoffLevel: 1
userTalkCats: [User talk]
contentTalkCats: [Person talk, Image talk, Givenname talk, Surname talk, Place talk, Source talk, Family talk, MySource talk, Repository talk]
globalCats: [Help talk, WeRelate talk, Template talk, Category talk]
complexPages: [2031061, 2723696, 7242635]
        #
# Identifying behavior variable, and how to collapse categories

behavior: active_days
editCats:
        simple_edits:
                - family_edits
                - person_edits
        local_talk_edits:
                - family_talk_edits
                - person_talk_edits
                - givenname_talk_edits
                - place_talk_edits
                - image_talk_edits
                - mysource_talk_edits
                - repository_talk_edits
                - source_talk_edits
                - surname_talk_edits
                - talk_edits
                - template_talk_edits
                - user_talk_edits
        community_talk_edits:
                - category_talk_edits
                - help_talk_edits
                - portal_talk_edits
                - werelate_talk_edits
        community_edits:
                - help_edits
                - werelate_edits
        complex_edits:
                - place_edits
                - category_edits
                - givenname_edits
                - image_edits
                - mysource_edits
                - portal_edits
                - repository_edits
                - source_edits
                - surname_edits
                - template_edits
                - transcript_edits
                - user_edits
        other_edits:
                - article_edits
                - mediawiki_edits
                - mediawiki_talk_edits
        all_edits:
                - all_edits
